version: '3'

services:
  django_db:
    image: postgres:12.3-alpine
    env_file: .env.db.dev
  django_app:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/django_app/
    env_file: .env.dev
    depends_on:
      - django_db
    ports:
      - 8000:8000
volumes:
  django_db: