# Generated by Django 3.1 on 2020-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
